---
- name: "Stage 1: Create directory for archives"
  file:
    path: "{{ direcory_pipeline }}"
    state: directory

- name: "Stage 2: Copy docker-compose file"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: tfs-user
    group: tfs-user
    mode: '0644'
  loop:
    - { src: "docker-compose.yml.j2", dest: "{{ direcory_pipeline }}/docker-compose.yml" }

- name: "Stage 2: Copy env file"
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: tfs-user
    group: tfs-user
    mode: '0644'
  loop:
    - { src: "files/{{ hostvars[inventory_hostname].group_names[0] }}/env", dest: "{{ direcory_pipeline }}/.env" }

- name: "Stage 3: Delete tg-bot container"
  community.docker.docker_container:
    name: tg-bot
    state: absent

- name: "Stage 4: Run containers"
  community.docker.docker_compose:
    project_name: tg-bot
    project_src: "{{ direcory_pipeline }}"
  register: output